import type { Component, Wire } from "./types";

function mcuPinName(mcu: Component, wires: Wire[], target: Component, pinId: string): number | string | null {
  const w = wires.find(
    (x) =>
      (x.fromComponentId === target.id && x.fromPinId === pinId && x.toComponentId === mcu.id) ||
      (x.toComponentId === target.id && x.toPinId === pinId && x.fromComponentId === mcu.id)
  );
  if (!w) return null;
  const mcuPinId = w.fromComponentId === mcu.id ? w.fromPinId : w.toPinId;
  const pin = mcu.pins.find((p) => p.id === mcuPinId);
  return pin?.number ?? mcuPinId;
}

export function generateSketch(components: Component[], wires: Wire[]): string {
  const mcu = components.find((c) => c.type.startsWith("arduino") || c.type === "esp32-s3");
  const lines: string[] = [];
  lines.push("/*");
  lines.push(" * Generated by VoltCraft AI Copilot");
  lines.push(" * Sketch matches the current canvas pin map.");
  lines.push(" */");
  lines.push("");

  const includes = new Set<string>();
  const globals: string[] = [];
  const setup: string[] = ["  Serial.begin(9600);"];
  const loop: string[] = [];

  if (!mcu) {
    return `${lines.join("\n")}\nvoid setup() {}\nvoid loop() {}\n`;
  }

  const leds = components.filter((c) => c.type.startsWith("led-"));
  leds.forEach((led, i) => {
    const p = mcuPinName(mcu, wires, led, "A");
    const name = `LED${i + 1}_PIN`;
    globals.push(`const int ${name} = ${p ?? 13};`);
    setup.push(`  pinMode(${name}, OUTPUT);`);
    loop.push(`  digitalWrite(${name}, HIGH);`);
    loop.push(`  delay(250);`);
    loop.push(`  digitalWrite(${name}, LOW);`);
    loop.push(`  delay(250);`);
  });

  const buttons = components.filter((c) => c.type === "pushbutton");
  buttons.forEach((b, i) => {
    const p = mcuPinName(mcu, wires, b, "1") ?? mcuPinName(mcu, wires, b, "2");
    const name = `BTN${i + 1}_PIN`;
    globals.push(`const int ${name} = ${p ?? 2};`);
    setup.push(`  pinMode(${name}, INPUT_PULLUP);`);
    loop.push(`  if (digitalRead(${name}) == LOW) {`);
    loop.push(`    Serial.println("Button ${i + 1} pressed");`);
    loop.push(`  }`);
  });

  const pots = components.filter((c) => c.type === "potentiometer");
  pots.forEach((p, i) => {
    const pin = mcuPinName(mcu, wires, p, "WIPER") ?? "A0";
    globals.push(`const int POT${i + 1}_PIN = ${pin};`);
    loop.push(`  int pot${i + 1} = analogRead(POT${i + 1}_PIN);`);
    loop.push(`  Serial.print("POT${i + 1}="); Serial.println(pot${i + 1});`);
  });

  const dhts = components.filter((c) => c.type === "dht11");
  if (dhts.length) {
    includes.add("#include <DHT.h>");
    dhts.forEach((d, i) => {
      const pin = mcuPinName(mcu, wires, d, "DATA") ?? 4;
      globals.push(`#define DHT${i + 1}_PIN ${pin}`);
      globals.push(`DHT dht${i + 1}(DHT${i + 1}_PIN, DHT11);`);
      setup.push(`  dht${i + 1}.begin();`);
      loop.push(`  float t${i + 1} = dht${i + 1}.readTemperature();`);
      loop.push(`  float h${i + 1} = dht${i + 1}.readHumidity();`);
      loop.push(`  Serial.print("Temp="); Serial.print(t${i + 1}); Serial.print("C Hum="); Serial.println(h${i + 1});`);
    });
  }

  const ultras = components.filter((c) => c.type === "hc-sr04");
  ultras.forEach((u, i) => {
    const trig = mcuPinName(mcu, wires, u, "TRIG") ?? 7;
    const echo = mcuPinName(mcu, wires, u, "ECHO") ?? 6;
    globals.push(`const int TRIG${i + 1} = ${trig};`);
    globals.push(`const int ECHO${i + 1} = ${echo};`);
    setup.push(`  pinMode(TRIG${i + 1}, OUTPUT);`);
    setup.push(`  pinMode(ECHO${i + 1}, INPUT);`);
    loop.push(`  digitalWrite(TRIG${i + 1}, LOW); delayMicroseconds(2);`);
    loop.push(`  digitalWrite(TRIG${i + 1}, HIGH); delayMicroseconds(10);`);
    loop.push(`  digitalWrite(TRIG${i + 1}, LOW);`);
    loop.push(`  long dur${i + 1} = pulseIn(ECHO${i + 1}, HIGH);`);
    loop.push(`  float dist${i + 1} = dur${i + 1} * 0.034 / 2;`);
    loop.push(`  Serial.print("Distance cm="); Serial.println(dist${i + 1});`);
  });

  const servos = components.filter((c) => c.type === "servo");
  if (servos.length) {
    includes.add("#include <Servo.h>");
    servos.forEach((s, i) => {
      const pin = mcuPinName(mcu, wires, s, "SIG") ?? 9;
      globals.push(`Servo servo${i + 1};`);
      setup.push(`  servo${i + 1}.attach(${pin});`);
      loop.push(`  servo${i + 1}.write(90);`);
    });
  }

  const lcds = components.filter((c) => c.type === "lcd-16x2-i2c");
  if (lcds.length) {
    includes.add("#include <Wire.h>");
    includes.add("#include <LiquidCrystal_I2C.h>");
    lcds.forEach((l, i) => {
      const addr = l.properties.address ?? "0x27";
      globals.push(`LiquidCrystal_I2C lcd${i + 1}(${addr}, 16, 2);`);
      setup.push(`  lcd${i + 1}.init();`);
      setup.push(`  lcd${i + 1}.backlight();`);
      setup.push(`  lcd${i + 1}.setCursor(0, 0);`);
      setup.push(`  lcd${i + 1}.print("VoltCraft AI");`);
      loop.push(`  lcd${i + 1}.setCursor(0, 1);`);
      loop.push(`  lcd${i + 1}.print(millis() / 1000);`);
    });
  }

  const oleds = components.filter((c) => c.type === "oled-ssd1306");
  if (oleds.length) {
    includes.add("#include <Wire.h>");
    includes.add("#include <Adafruit_SSD1306.h>");
    globals.push("Adafruit_SSD1306 display(128, 64, &Wire, -1);");
    setup.push("  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);");
    setup.push("  display.clearDisplay();");
    setup.push('  display.println("VoltCraft");');
    setup.push("  display.display();");
  }

  const buzz = components.filter((c) => c.type === "buzzer");
  buzz.forEach((b, i) => {
    const p = mcuPinName(mcu, wires, b, "SIG") ?? 8;
    globals.push(`const int BUZZ${i + 1} = ${p};`);
    setup.push(`  pinMode(BUZZ${i + 1}, OUTPUT);`);
  });

  const rgb = components.filter((c) => c.type === "rgb-led");
  rgb.forEach((r) => {
    const rp = mcuPinName(mcu, wires, r, "R") ?? 9;
    const gp = mcuPinName(mcu, wires, r, "G") ?? 10;
    const bp = mcuPinName(mcu, wires, r, "B") ?? 11;
    globals.push(`const int RGB_R = ${rp}, RGB_G = ${gp}, RGB_B = ${bp};`);
    setup.push("  pinMode(RGB_R, OUTPUT); pinMode(RGB_G, OUTPUT); pinMode(RGB_B, OUTPUT);");
    loop.push("  analogWrite(RGB_R, 80); analogWrite(RGB_G, 20); analogWrite(RGB_B, 160);");
  });

  if (!loop.length) {
    loop.push('  Serial.println("loop");');
    loop.push("  delay(1000);");
  } else {
    loop.push("  delay(200);");
  }

  const out = [
    ...lines,
    ...includes,
    includes.size ? "" : "",
    ...globals,
    "",
    "void setup() {",
    ...setup,
    "}",
    "",
    "void loop() {",
    ...loop,
    "}",
    "",
  ];
  return out.filter((l, i, a) => !(l === "" && a[i - 1] === "")).join("\n");
}
