import { componentRegistry } from "./registry";
import type { ComponentCategory, UniversalComponentSchema, UniversalPinType } from "./schema";

type Seed = [id: string, name: string, category: ComponentCategory, profile: string];
const seeds: Seed[] = [
  ["arduino-uno-r4","Arduino Uno R4","Board","board"],["arduino-nano","Arduino Nano","Board","board"],["arduino-leonardo","Arduino Leonardo","Board","board"],["esp32-devkitc","ESP32 DevKitC","Board","board"],["esp32-c3","ESP32-C3","Board","board"],["raspberry-pi-pico","Raspberry Pi Pico","Board","board"],["stm32-blue-pill","STM32F103 Blue Pill","Board","board"],["attiny85","ATtiny85","Board","dip"],
  ["lcd-20x4-i2c","20x4 LCD I2C","Display","i2c"],["lcd-20x4-parallel","20x4 LCD Parallel","Display","display"],["oled-sh1106-i2c","SH1106 OLED I2C","Display","i2c"],["oled-ssd1306-spi","SSD1306 OLED SPI","Display","spi"],["tft-st7735","ST7735 TFT","Display","spi"],["seven-seg-4","4-Digit 7-Segment","Display","display"],["tm1637-display","TM1637 Display","Display","digital"],["max7219-matrix","MAX7219 8x8 Matrix","Display","spi"],["neopixel-strip","WS2812B NeoPixel Strip","Display","pixel"],["sk6812-strip","SK6812 RGBW Strip","Display","pixel"],["epaper-display","E-Paper Display","Display","spi"],
  ["dht22","DHT22","Sensor","sensor"],["jsn-sr04t","JSN-SR04T Ultrasonic","Sensor","ultrasonic"],["mq-2","MQ-2 Gas Sensor","Sensor","analog"],["mq-135","MQ-135 Air Quality","Sensor","analog"],["mpu6050","MPU6050 IMU","Sensor","i2c"],["ir-receiver","IR Receiver","Sensor","digital"],["ir-obstacle","IR Obstacle Sensor","Sensor","digital"],["ds18b20","DS18B20 OneWire","Sensor","digital"],["bmp280","BMP280","Sensor","i2c"],["bme280","BME280","Sensor","i2c"],["rotary-encoder","Rotary Encoder","Input","encoder"],["flex-sensor","Flex Sensor","Sensor","passive"],["fsr","Force Sensitive Resistor","Sensor","passive"],["tcs3200","TCS3200 Color Sensor","Sensor","digital"],["soil-moisture","Soil Moisture Sensor","Sensor","analog"],["rain-sensor","Rain Sensor","Sensor","analog"],
  ["servo-sg90","SG90 Servo","Actuator","servo"],["servo-mg996r","MG996R Servo","Actuator","servo"],["stepper-28byj48","28BYJ-48 Stepper","Actuator","motor"],["uln2003","ULN2003 Driver","IC","driver"],["nema17","NEMA 17 Stepper","Actuator","motor"],["a4988","A4988 Stepper Driver","IC","driver"],["drv8825","DRV8825 Stepper Driver","IC","driver"],["l293d","L293D H-Bridge","IC","driver"],["tb6612fng","TB6612FNG Driver","IC","driver"],["relay-5v","5V Mechanical Relay","Actuator","relay"],["relay-12v","12V Mechanical Relay","Actuator","relay"],["solid-state-relay","Solid State Relay","Actuator","relay"],["solenoid","Solenoid","Actuator","motor"],["vibration-motor","Vibration Motor","Actuator","motor"],
  ["active-buzzer","Active Buzzer","Audio","audio"],["piezo-passive","Passive Piezo","Audio","audio"],["pam8403","PAM8403 Amplifier","Audio","audio"],["dfplayer-mini","DFPlayer Mini","Audio","uart"],
  ["toggle-switch","Toggle Switch","Input","switch"],["slide-potentiometer","Slide Potentiometer","Input","analog"],["keypad-3x4","3x4 Matrix Keypad","Input","keypad"],
  ["capacitor-ceramic","Ceramic Capacitor","Passive","passive"],["capacitor-electrolytic","Electrolytic Capacitor","Passive","passive"],["inductor","Inductor","Passive","passive"],["diode-1n4007","1N4007 Diode","Semiconductor","passive"],["diode-1n4148","1N4148 Diode","Semiconductor","passive"],["zener-diode","Zener Diode","Semiconductor","passive"],["led-5mm","5mm LED","Semiconductor","passive"],["bc547","BC547 NPN","Semiconductor","transistor"],["2n2222","2N2222 NPN","Semiconductor","transistor"],["pnp-transistor","PNP Transistor","Semiconductor","transistor"],["irfz44n","IRFZ44N MOSFET","Semiconductor","transistor"],["pc817","PC817 Optocoupler","Semiconductor","dip"],
  ["74hc595","74HC595 Shift Register","IC","dip"],["74hc165","74HC165 Shift Register","IC","dip"],["cd4051","CD4051 Multiplexer","IC","dip"],["ds3231","DS3231 RTC","IC","i2c"],["microsd-module","MicroSD Module","IC","spi"],["at24c256","AT24C256 EEPROM","IC","i2c"],
  ["hc-05","HC-05 Bluetooth","Communication","uart"],["hc-06","HC-06 Bluetooth","Communication","uart"],["nrf24l01","NRF24L01+","Communication","spi"],["logic-level-converter","Logic Level Converter","Power","digital"],["lm2596","LM2596 Buck Converter","Power","power"],["breadboard-psu","Breadboard Power Supply","Power","power"],["battery-9v","9V Battery","Power","power"],["cell-18650","18650 Li-ion Cell","Power","power"],["usb-5v","USB 5V Rail","Power","power"]
];

const profiles: Record<string, [string, UniversalPinType][]> = {
 board:[["GND","gnd"],["3V3","power"],["GPIO0","digital"],["GPIO1","digital"],["SDA","i2c"],["SCL","i2c"],["MOSI","spi"],["MISO","spi"]], dip:[["VCC","power"],["GND","gnd"],["IN","digital"],["OUT","digital"]], i2c:[["GND","gnd"],["VCC","power"],["SDA","i2c"],["SCL","i2c"]], spi:[["GND","gnd"],["VCC","power"],["SCK","spi"],["MOSI","spi"],["MISO","spi"],["CS","digital"]], uart:[["GND","gnd"],["VCC","power"],["TX","uart"],["RX","uart"]], passive:[["1","passive"],["2","passive"]], analog:[["GND","gnd"],["VCC","power"],["AO","analog"],["DO","digital"]], digital:[["GND","gnd"],["VCC","power"],["DATA","digital"]], sensor:[["GND","gnd"],["VCC","power"],["DATA","digital"]], ultrasonic:[["VCC","power"],["TRIG","digital"],["ECHO","digital"],["GND","gnd"]], servo:[["GND","gnd"],["VCC","power"],["PWM","digital"]], motor:[["A","passive"],["B","passive"]], relay:[["VCC","power"],["GND","gnd"],["IN","digital"],["COM","passive"],["NO","passive"],["NC","passive"]], audio:[["GND","gnd"],["VCC","power"],["SIG","digital"]], power:[["VIN","power"],["GND","gnd"],["VOUT","power"]], transistor:[["G","digital"],["D","passive"],["S","gnd"]], switch:[["COM","passive"],["NO","passive"],["NC","passive"]], encoder:[["GND","gnd"],["VCC","power"],["CLK","digital"],["DT","digital"],["SW","digital"]], driver:[["GND","gnd"],["VCC","power"],["IN1","digital"],["IN2","digital"],["OUT1","passive"],["OUT2","passive"]], display:[["GND","gnd"],["VCC","power"],["D0","digital"],["D1","digital"],["D2","digital"],["D3","digital"]], pixel:[["GND","gnd"],["VCC","power"],["DIN","digital"],["DOUT","digital"]], keypad:[["R1","digital"],["R2","digital"],["R3","digital"],["R4","digital"],["C1","digital"],["C2","digital"],["C3","digital"]]
};

function make([id,name,category,profile]: Seed): UniversalComponentSchema {
  const width = category === "Board" ? 150 : category === "Display" ? 110 : 76, height = category === "Board" ? 76 : 58;
  const pp = profiles[profile] ?? profiles.digital;
  const pins = pp.map(([label,type], i) => ({ id:label,label,type,xPct:i%2?1:0,yPct:(Math.floor(i/2)+1)/(Math.ceil(pp.length/2)+1) }));
  const color = category === "Sensor" ? "#0f766e" : category === "Actuator" ? "#7c2d12" : category === "Board" ? "#075985" : "#283548";
  return { id, name, category, description:`Simulation-ready ${name} plugin`, dimensions:{width,height,unit:"px"}, pins, properties:{enabled:{type:"boolean",default:true}}, interactiveControls: category === "Sensor" ? [{type:"environment_popover",targetPinOrProperty:"value",min:0,max:1023}] : undefined, tags:[category.toLowerCase(),profile], svgAsset:`<rect width="${width}" height="${height}" rx="7" fill="${color}" stroke="#64748b"/><rect x="7" y="7" width="${width-14}" height="${height-14}" rx="4" fill="#0b1220" opacity=".45"/><text x="${width/2}" y="${height/2+4}" text-anchor="middle" font-size="10" font-family="sans-serif" fill="#e2e8f0">${name}</text>` };
}

export const BUILTIN_COMPONENTS = seeds.map(make);
componentRegistry.registerMany(BUILTIN_COMPONENTS, true);
